name: bowenfan-chisel
base: core24
version: '1.0'
summary: chisel
description: chisel

grade: devel
confinement: devmode

apps:
  chisel:
    command: bin/chisel
  chrorder:
    command: bin/chrorder

parts:
  pretty:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-pretty
    source-type: git
    source-branch: 0.2-24.04_edge
    plugin: nil
    override-stage: ""
  text:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-text
    source-type: git
    source-branch: 0.1-24.04_edge
    plugin: nil
    override-stage: ""
  sys:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-sys
    source-type: git
    source-branch: 0.18-24.04_edge
    plugin: nil
    override-stage: ""
  ar:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-ar
    source-type: git
    source-branch: 0.1-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
  go-flags:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-go-flags
    source-type: git
    source-branch: 1.5-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
  fslock:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-fslock
    source-type: git
    source-branch: 0.1-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
  compress:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-compress
    source-type: git
    source-branch: 1.15-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
  xz:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-xz
    source-type: git
    source-branch: 0.5-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
  starlark-go:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-starlark-go
    source-type: git
    source-branch: 0.1-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
  crypto:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-crypto
    source-type: git
    source-branch: 0.21-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
  term:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-term
    source-type: git
    source-branch: 0.18-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
  check-v1:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-check-v1
    source-type: git
    source-branch: 1.0-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
  yaml-v3:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-yaml-v3
    source-type: git
    source-branch: 3.0-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
  chisel:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-chisel
    source-type: git
    source-branch: 1.0-24.04_edge
    plugin: go
    build-snaps:
      - go/1.21/stable
    after: [ar, go-flags, fslock, compress, xz, starlark-go, crypto, term, check-v1, yaml-v3]
    override-build: |
      BASE_PARTS_PATH=${CRAFT_PART_SRC%%/chisel*}
      cd $CRAFT_PART_SRC
      go env -w GOPROXY=off GONOSUMDB=git.staging.snapcraftcontent.com GOPRIVATE=git.staging.snapcraftcontent.com
      go work init
      go work use $CRAFT_PART_SRC
      go work use $BASE_PARTS_PATH/pretty/src
      go work use $BASE_PARTS_PATH/text/src
      go work use $BASE_PARTS_PATH/sys/src
      go work use $BASE_PARTS_PATH/ar/src
      go work use $BASE_PARTS_PATH/go-flags/src
      go work use $BASE_PARTS_PATH/fslock/src
      go work use $BASE_PARTS_PATH/compress/src
      go work use $BASE_PARTS_PATH/xz/src
      go work use $BASE_PARTS_PATH/starlark-go/src
      go work use $BASE_PARTS_PATH/crypto/src
      go work use $BASE_PARTS_PATH/term/src
      go work use $BASE_PARTS_PATH/check-v1/src
      go work use $BASE_PARTS_PATH/yaml-v3/src
      mkdir -p $CRAFT_STAGE/bin
      go build -o $CRAFT_STAGE/bin/ ./...
    override-stage: ""
    override-prime: |
      cp -r $CRAFT_STAGE/bin $CRAFT_PRIME/bin
    build-environment:
      - GOPROXY: 'off'
      - GONOSUMDB: git.staging.snapcraftcontent.com
      - GOPRIVATE: git.staging.snapcraftcontent.com
