name: superalpaca-chisel
base: core24
version: '1.0'
summary: chisel
description: chisel

grade: devel
confinement: devmode

environment:
  SNAPD_DEBUG: "1"
  SNAPD_DEBUG_HTTP: "7"
  SNAP_CLIENT_DEBUG_HTTP: "7"
  GIT_TRACE_REDACT: "0"
  GIT_CURL_VERBOSE: "1"
  GIT_TRACE: "1"
  CRAFT_VERBOSITY_LEVEL: "trace"
  SNAPCRAFT_VERBOSITY_LEVEL: "trace"


apps:
  chisel:
    command: bin/chisel
  chrorder:
    command: bin/chrorder

parts:
  env:
    plugin: nil
    override-pull: |
      # export GIT_ORIG=$(which git)
      # echo GIT_ORIG
      ls -al /usr/bin | grep git
      # cp /usr/bin/git /usr/bin/git.orig
      # ls -al $CRAFT_PROJECT_DIR
      cp $CRAFT_PROJECT_DIR/git-wrapper /usr/bin/git-wrapper
      mv /usr/bin/git /usr/bin/git.orig
      ln -s /usr/bin/git-wrapper /usr/bin/git
      ls -al /usr/bin | grep git
      export CRAFT_VERBOSITY_LEVEL=trace
      export SNAPCRAFT_VERBOSITY_LEVEL=trace
      ls -al/root
      ls -al /root/.local/state/snapcraft/log
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  pretty:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-pretty
    source-type: git
    source-depth: 1
    source-branch: 0.2-24.04_edge
    plugin: nil
    override-stage: ""
    after: [env]
    override-pull: |
      echo "PRETTY"
      echo "HERE"
      env | grep -i craft
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  text:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-text
    source-type: git
    source-depth: 1
    source-branch: 0.1-24.04_edge
    plugin: nil
    override-stage: ""
    after: [env]
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  sys:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-sys
    source-type: git
    source-depth: 1
    source-branch: 0.18-24.04_edge
    plugin: nil
    override-stage: ""
    after: [env]
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  ar:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-ar
    source-type: git
    source-depth: 1
    source-branch: 0.1-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  go-flags:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-go-flags
    source-type: git
    source-depth: 1
    source-branch: 1.5-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  fslock:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-fslock
    source-type: git
    source-depth: 1
    source-branch: 0.1-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  compress:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-compress
    source-type: git
    source-depth: 1
    source-branch: 1.15-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  xz:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-xz
    source-type: git
    source-depth: 1
    source-branch: 0.5-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  starlark-go:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-starlark-go
    source-type: git
    source-depth: 1
    source-branch: 0.1-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  crypto:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-crypto
    source-type: git
    source-depth: 1
    source-branch: 0.21-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  term:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-term
    source-type: git
    source-depth: 1
    source-branch: 0.18-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  check-v1:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-check-v1
    source-type: git
    source-depth: 1
    source-branch: 1.0-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  yaml-v3:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-yaml-v3
    source-type: git
    source-depth: 1
    source-branch: 3.0-24.04_edge
    plugin: nil
    after: [pretty, text, sys]
    override-stage: ""
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
  chisel:
    source: https://git.staging.snapcraftcontent.com/ubuntu/public/sourcecraft/bowenfan-chisel
    source-type: git
    source-depth: 1
    source-branch: 1.0-24.04_edge
    plugin: go
    build-snaps:
      - go/1.21/stable
    after: [ar, go-flags, fslock, compress, xz, starlark-go, crypto, term, check-v1, yaml-v3]
    override-pull: |
      craftctl default || true
      tail -n 500 /tmp/snapcraft.log > /tmp/testlog
      cat /tmp/testlog
    override-build: |
      # undo hack
      rm /usr/bin/git
      ls -al /usr/bin | grep git
      ln -s /usr/bin/git.orig /usr/bin/git
      ls -al /usr/bin | grep git
      BASE_PARTS_PATH=${CRAFT_PART_SRC%%/chisel*}
      cd $CRAFT_PART_SRC
      go env -w GOPROXY=off GONOSUMDB=git.staging.snapcraftcontent.com GOPRIVATE=git.staging.snapcraftcontent.com
      go work init
      go work use $CRAFT_PART_SRC
      go work use $BASE_PARTS_PATH/pretty/src
      go work use $BASE_PARTS_PATH/text/src
      go work use $BASE_PARTS_PATH/sys/src
      go work use $BASE_PARTS_PATH/ar/src
      go work use $BASE_PARTS_PATH/go-flags/src
      go work use $BASE_PARTS_PATH/fslock/src
      go work use $BASE_PARTS_PATH/compress/src
      go work use $BASE_PARTS_PATH/xz/src
      go work use $BASE_PARTS_PATH/starlark-go/src
      go work use $BASE_PARTS_PATH/crypto/src
      go work use $BASE_PARTS_PATH/term/src
      go work use $BASE_PARTS_PATH/check-v1/src
      go work use $BASE_PARTS_PATH/yaml-v3/src
      mkdir -p $CRAFT_STAGE/bin
      go build -o $CRAFT_STAGE/bin/ ./...
    override-stage: ""
    override-prime: |
      cp -r $CRAFT_STAGE/bin $CRAFT_PRIME/bin
    build-environment:
      - GOPROXY: 'off'
      - GONOSUMDB: git.staging.snapcraftcontent.com
      - GOPRIVATE: git.staging.snapcraftcontent.com
